config/routes.rb
Rails.application.routes.draw do
  root :to=> 'chapters#index'

  resources :chapters do
    resources :sections, :except => [:index] do
      resources :lessons, :except => [:show, :index]
    end
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :sections
  validates :title, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  belongs_to :chapter
  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
    render :index
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def new
    @chapter = Chapter.new
    render :new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      redirect_to chapters_path
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    destroyed_chapter_title = @chapter.title
    @chapter.destroy
    redirect_to chapters_path
  end

private
  def chapter_params
    params.require(:chapter).permit(:title)
  end

end

app/controllers/lessons_controller.rb
class LessonsController <ApplicationController
  def new
    @section =  Section.find(params[:section_id])
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = @section.lessons.new
  end

  def create
    @section = Section.find(params[:section_id])
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to chapter_section_lesson_path(@lesson.section.chapter)
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:section_id])
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = Lesson.find(params[:id])
  end

  def update
    @section = Section.find(params[:section_id])
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = Lesson.find(params[:id])
    old_title = @lesson.title
    if @lesson.update(lesson_params)
      redirect_to section_path(@lesson.section)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:section_id])
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = Lesson.find(params[:id])
    destroyed_lesson_title = @lesson.title
    @lesson.destroy
    redirect_to section_path(@lesson.section)
  end

  private
  def lesson_params
    params.require(:lesson).permit(:title)
    params.require(:lesson).permit(:content)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new(section_params)
    if @section.save
      redirect_to chapter_path(@section.chapter)
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
    old_title = @section.title
    if @section.update(section_params)
      redirect_to chapter_path(@section.chapter)
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
    destroyed_section_title = @section.title
    @section.destroy
    redirect_to chapter_path(@section.chapter)
  end

  private
    def section_params
      params.require(:section).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= form_for @chapter do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<h4>Edit Chapter Title</h4>

<%= render 'form' %>

app/views/chapters/index.html.erb
<% content_for(:title, 'Epiclonus') %>

<h4>Chapters</h4>

  <% @chapters.each do |chapter| %>
    <div>
      <%= link_to chapter.title, chapter_path(chapter) %>
      <ul>
      <% chapter.sections.each do |section| %>

        <li><%= section.title %>
          <ul>
            <% section.lessons.each do |lesson| %>
            <li><%=  lesson.title %> </li>
            <% end %>
          </ul>
        </li>
        <% end %>
      <ul>
    </div>

  <% end %>

<%= link_to 'Make a new Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h4>New Chapter</h4>

<%= render 'form' %>

app/views/chapters/show.html.erb
<% content_for(:title, "Epiclonus") %>
<h4>
  <%= @chapter.title %>
</h4>
  <%= link_to edit_chapter_path(@chapter) do %> Edit <% end %>
  <%= link_to chapter_path(@chapter), :data => {:confirm =>'Send into digital oblivion.', :method => 'delete'} do %> Delete <% end %>

  <%= link_to new_chapter_section_path(@chapter) do %>
  Add Section
  <% end %>

  <% if @chapter.sections.any? %>
    <h4>Sections:</h4>

    <ul>
      <% @chapter.sections.each do |section| %>
      <li><%= link_to section.title, chapter_section_path(@chapter, section) %> |
        <ul>
          <% section.lessons.each do |lesson| %>
          <li><%=  lesson.title %> </li>
          <% end %>
        </ul>
      </li>
      <% end %>
    </ul>

  <% else %>

  <p>No sections. </p>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container">

      <%= yield %>

  </div>
  
</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for [@chapter, @section, @lesson] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h4>Edit Lesson</h4>

<%= render 'form' %>

app/views/lessons/new.html.erb
<% content_for(:title, 'Epiclonus | New Lesson') %>

<h4>New lesson for <%= @section.title %></h4>

<%= render 'form' %>

app/views/sections/_form.html.erb
<%= form_for [@chapter, @section] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h4>Edit Section</h4>

<%= render 'form' %>

app/views/sections/new.html.erb
<% content_for(:title, 'Epiclonus | New Section') %>

<h4>New section for <%= @chapter.title %></h4>

<%= render 'form' %>

app/views/sections/show.html.erb
<% content_for(:title, "Epiclonus") %>
<h4>
  <%= @chapter.title %>
  <%= @section.title %>
</h4>
<%= link_to edit_chapter_section_path(@chapter, @section) do %> Edit <% end %> |
<%= link_to chapter_section_path(@chapter, @section), :data => {:confirm => 'Send section into digital oblivion?', :method => 'delete'} do %> Delete <% end %>

<%= link_to new_chapter_section_lesson_path(@chapter, @section) do %>
Add Lesson
<% end %>